#!/usr/bin/env bash
# -------------------------------------------------------------
#  makecrandist.sh - creates the CRAN source tarball
#
#  Result:  <project>/triplclustLibR/triplclust_<version>.tar.gz
#
#  Everything happens in a temporary directory, so the
#  repository itself is never modified.
# -------------------------------------------------------------
set -euo pipefail

# ---------- Paths ----------
R_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"   # triplclustLibR/
ROOT="$(dirname "${R_DIR}")"                            # repository root
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || exit 1

WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT                            # always clean up
PKG="${WORK}/triplclust"                                # temporary package

# ---------- Step 1: copy the R package ----------
mkdir -p "${PKG}"
cp -a "${R_DIR}"/* "${PKG}"
cd "${PKG}"

# Remove files that do not belong into the CRAN package
rm -f makecrandist.sh build.sh clean.sh clean_build.sh verify.sh build.R
rm -f src/*.o src/*.so src/RcppExports.*

# ---------- Step 2: license ----------
# lic_cran (CRAN's short format) becomes the package LICENSE.
# mkdir -p inst
# cp LICENSE inst/COPYRIGHTS
# mv lic_cran LICENSE

# ---------- Step 3: copy the C++ sources ----------
cp -r "${ROOT}/src/hclust" "${ROOT}/src/kdtree" src/
cp "${ROOT}"/src/*.cpp "${ROOT}"/src/*.h src/

# These two are only needed for the standalone binary
rm src/main.cpp src/option.cpp

# R compiles only the .cpp files directly in src/, so move them up.
# The fastcluster_*dm.cpp files stay in hclust/ because they are #included.
mv src/hclust/fastcluster.cpp src/
mv src/kdtree/kdtree.cpp src/

# ---------- Step 4: adapt the sources for CRAN ----------
# (a) remove warning-suppression pragmas
sed -i -e '/^[[:space:]]*#pragma GCC diagnostic /d' \
       src/*.cpp src/hclust/*.cpp

# (c) CRAN forbids std::cout / std::cerr: use Rcpp::Rcout instead
for f in $(grep -lE 'std::(cout|cerr)' src/*.cpp || true); do
  sed -i -e 's/std::cout/Rcpp::Rcout/g' -e 's/std::cerr/Rcpp::Rcout/g' "$f"
  sed -i '1i #include <Rcpp.h>' "$f"
done

# ---------- Step 5: generate Rcpp glue code and documentation ----------
# Rcpp requires NAMESPACE to recognize the package directory; the marker lets
# roxygen2 replace this placeholder with the generated namespace.
if [[ ! -f NAMESPACE ]]; then
  printf '%s\n' '# Generated by roxygen2: do not edit by hand' > NAMESPACE
fi
Rscript -e "Rcpp::compileAttributes('.')"
Rscript -e "roxygen2::roxygenise('.', roclets = c('namespace', 'collate', 'rd'))"

# ---------- Step 6: build the tarball ----------
cd "${WORK}"
R CMD build triplclust
mv triplclust_*.tar.gz "${R_DIR}/"

echo "Tarball created in: ${R_DIR}/"
